
  win_size: 400
  stride: 200
  min_mapq: 10
  apply_depth: true
  depth_max_ratio: 1.75
  depth_min_ratio: 0.15
  max_diff_ratio: 0.2     # 插入删除的不一致比例  hifi:0.15, ont:0.2
  check_win_size: 10000 # 10000/8000/6000  / 6000 for hifi   / 10000 for ONT
  min_distance: 0.3
  contig_block_size: 1000000

  min_clip_len: 500 # 超过这个长度的认为是异常clip。abnormal clip。需要对hifi数据和ont数据的clip进行一定的统计
  min_clip_num: 5   # 超过这个数目，认为是异常区域。与覆盖度有关，需要对覆盖度进行一定的分析
  apply_clip: true
  clip_params:
    min_clip_portion: 0.35  # 0.25
    clip_win_size: 1000 #
    min_MQ: 0  # keep with dp
  apply_pileup: true
  pileup_params:
    min_correct_portion: 0.9    # 一致性比例（类似identity）hifi:0.95, ont:0.9
    max_differ_portion: 0.2     # 插入删除的不一致比例  hifi:0.15, ont:0.2
    max_disagree_portion: 0.1  # 单碱基不一致比例，用来暗示一些隐含的比对错误区域。但是对某些生物，基因组可能存在大量的snp，就需要把值开大点，或者对于高错误率读数，同理  hifi:0.05, ont:0.1
    cluster_dis: 1000
  filter2:
    bound_span: 10000 # bound skip
    check_win_size: 10000 # 10000/8000/6000  / 6000 for hifi   / 10000 for ONT
    min_span_num: 3   # 2 for hifi, 3 for ont
    min_supp_portion: 0.4  # 有多少成的读数表明没有mis
    min_MQ: 1    # 20/3/1。hifi_asm    map_Q太严了，导致大量的比对过滤掉了->3。hifi_asm:3
    MIN_ALIGN_LENGTH: 10000
    MIN_ALIGN_RATE: 0.95
    ins_threshold: 100
    del_threshold: 100
    min_clip_len: 500


